name: Build Toolchain

on:
  push:
    branches:
      - swiftwasm
      - swiftwasm-release/5.3
      - swiftwasm-release/5.4
      - swiftwasm-release/5.5
      - swiftwasm-release/5.6
  pull_request:
    branches:
      - swiftwasm
      - swiftwasm-release/5.3
      - swiftwasm-release/5.4
      - swiftwasm-release/5.5
      - swiftwasm-release/5.6
jobs:
  build_toolchain:
    env:
      TOOLCHAIN_CHANNEL: DEVELOPMENT
      DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer/
    strategy:
      matrix:
        include:
          - build_os: ubuntu-18.04
            agent_query: ubuntu-18.04
            target: ubuntu18.04_x86_64
            run_stdlib_test: true
            run_full_test: false
            run_e2e_test: true
            build_hello_wasm: true
            clean_build_dir: false

          - build_os: ubuntu-20.04
            agent_query: ubuntu-20.04
            target: ubuntu20.04_x86_64
            run_stdlib_test: true
            run_full_test: false
            run_e2e_test: true
            build_hello_wasm: true
            clean_build_dir: false

          - build_os: macos-11
            agent_query: macos-11
            target: macos_x86_64
            run_stdlib_test: true
            run_full_test: true
            run_e2e_test: true
            build_hello_wasm: true
            clean_build_dir: false

          - build_os: macos-11
            agent_query: [self-hosted, macOS, ARM64]
            target: macos_arm64
            # FIXME: Enable stdlib test after wasmer fixes singlepass bug on arm64,
            # fixes cranelift bug on x64, or wasmtime supports arm64
            # Currently it's hard to run tests on both x64 and arm64.
            run_stdlib_test: false
            run_full_test: false
            run_e2e_test: false
            build_hello_wasm: true
            clean_build_dir: true

    name: Target ${{ matrix.target }}
    timeout-minutes: 0
    runs-on: ${{ matrix.agent_query }}
    steps:
      # TODO(katei): Remove this step after https://bugs.swift.org/browse/SR-15135 will be resolved
      - name: (Workaround) Uninstall pre-installed Swift toolchain on Linux
        if: ${{ matrix.build_os == 'ubuntu-20.04' || matrix.build_os == 'ubuntu-18.04' }}
        run: |
          # Installer script is here: https://github.com/actions/virtual-environments/blob/1cbea058249db750691ec74f1b3ba9a7b1605d26/images/linux/scripts/installers/swift.sh
          rm -f /usr/local/bin/swiftc /usr/local/bin/swift
          rm -rf /usr/share/swift/

      - name: Free disk space
        if: ${{ matrix.build_os == 'ubuntu-20.04' || matrix.build_os == 'ubuntu-18.04' }}
        run: |
          df -h
          sudo apt-get purge libgcc-9-dev gcc-9 libstdc++-9-dev libgcc-10-dev gcc-10 libstdc++-10-dev clang-6.0 llvm-6.0
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo rm -rf /opt/hostedtoolcache
          sudo rm -rf /usr/share/dotnet
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h

      - uses: actions/checkout@v2
        with:
          path: swift
          fetch-depth: 0

      - name: Prepare sccache timestamp
        id: cache_timestamp
        shell: cmake -P {0}
        run: |
          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
          message("::set-output name=timestamp::${current_date}")

      - name: Check Xcode version
        if: ${{ startsWith(matrix.build_os, 'macos-') }}
        run: |
          xcodebuild -version

      - uses: actions/cache@v1
        with:
          path: build-cache
          key: ${{ matrix.target }}-sccache-v11-${{ steps.cache_timestamp.outputs.timestamp }}
          restore-keys: |
            ${{ matrix.target }}-sccache-v11-

      - name: Clean stdlib build directory
        if: ${{ matrix.clean_build_dir }}
        run: |
          rm -rf ${{ github.workspace }}/target-build \
            ${{ github.workspace }}/host-build \
            ${{ github.workspace }}/host-toolchain-sdk \
            ${{ github.workspace }}/dist-toolchain-sdk

      - name: Build ${{ matrix.target }} installable archive
        env:
          SKIP_XCODE_VERSION_CHECK: 1
        run: |

          case "${{ matrix.target }}" in
            "ubuntu20.04_x86_64" | "ubuntu18.04_x86_64" | "macos_x86_64" | "macos_arm64")
              ./swift/utils/webassembly/ci.sh
            ;;
            *)
              echo "Unrecognised target: ${{ matrix.target }}"
              exit 1
            ;;
          esac

      - name: Check cache hit rate
        run: sccache --show-stats

      - name: Upload ${{ matrix.target }} installable archive
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.target }}-installable
          path: swift-wasm-${{ env.TOOLCHAIN_CHANNEL }}-SNAPSHOT-${{ matrix.target }}.tar.gz

      - name: Add wasmer in PATH for testing
        run: echo "$HOME/.wasmer/bin" >> $GITHUB_PATH

      - name: Run stdlib tests for wasi-wasm32
        if: ${{ matrix.run_stdlib_test }}
        run: |
          TARGET_STDLIB_BUILD_DIR=${{ github.workspace }}/target-build/swift-stdlib-wasi-wasm32
          ninja check-swift-wasi-wasm32-custom -C "$TARGET_STDLIB_BUILD_DIR"

      - name: Run all tests for wasi-wasm32
        if: ${{ matrix.run_full_test }}
        run: |
          TARGET_STDLIB_BUILD_DIR=${{ github.workspace }}/target-build/swift-stdlib-wasi-wasm32
          # Run all tests but ignore failure temporarily
          ninja check-swift-wasi-wasm32 -C "$TARGET_STDLIB_BUILD_DIR" || true

      - name: Pack test results
        if: ${{ matrix.run_full_test }}
        run: |
          tar cJf ./swift-test-results.tar.gz target-build/swift-stdlib-wasi-wasm32/swift-test-results
      - name: Upload test results
        uses: actions/upload-artifact@v1
        if: ${{ matrix.run_full_test }}
        with:
          name: ${{ matrix.target }}-test-results
          path: ./swift-test-results.tar.gz

      # Run e2e test
      - name: Prepare E2E test
        run: |
          INSTALL_DIR=$(mktemp -d)
          tar xf swift-wasm-$TOOLCHAIN_CHANNEL-SNAPSHOT-${{ matrix.target }}.tar.gz -C "$INSTALL_DIR"
          echo "TOOLCHAIN=$(find "$INSTALL_DIR" -name "swift-wasm-$TOOLCHAIN_CHANNEL-*" -type d | head -n1)" >> $GITHUB_ENV
      - name: Build hello.wasm
        shell: bash
        if: ${{ matrix.build_hello_wasm }}
        run: |
          echo 'print("Hello, world!")' > hello.swift
          $TOOLCHAIN/usr/bin/swiftc \
                -target wasm32-unknown-wasi \
                -sdk $TOOLCHAIN/usr/share/wasi-sysroot \
                hello.swift -o hello.wasm && \
                echo "Successfully linked hello.wasm"
      - name: Upload hello.wasm
        if: ${{ matrix.build_hello_wasm }}
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.target }}-hello.wasm
          path: hello.wasm
      - name: Checkout integration-tests
        if: ${{ matrix.run_e2e_test }}
        uses: actions/checkout@v2
        with:
          repository: swiftwasm/integration-tests
          path: integration-tests
      - name: Run integration tests
        if: ${{ matrix.run_e2e_test }}
        run: |
          $TOOLCHAIN/usr/bin/swift run # Use TOOLCHAIN env value
        working-directory: ${{ github.workspace }}/integration-tests
